import Search from "./Search";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex space-x-4 divide-x-2 p-5">
      <div>
        <h1>Search</h1>
      </div>
      <div className="flex-1 pl-5">
        <Search />
        <div className="">{children}</div>
      </div>
    </main>
  );
}
